languageCode = 'en-US'
languageName = 'EN'
weight = 2

title = 'Dice Irae'
copyright = 'All Rights Reserved'

[author]
    name = "Bilow"
    description = "Game Master out for XP and cool."
    email = "contact@dice-irae.com"
